Algoritmo "soma"

//Fazer um programa para ler dois valores inteiros X e Y,
//e depois mostrar na tela o valor da soma destes números.

//Digite o valor de X: 8
//Digite o valor de Y: 10
//SOMA = 18
Var
    valor1,valor2: inteiro
    soma: inteiro
Inicio
       escreva("Digite o valor de x: ")
       leia(valor1)
       escreva("Digite o valor de y:")
       leia(valor2)
       soma <- valor1+valor2
       escreva("A soma eh: ",soma)

Fimalgoritmo